# Generated by Django 4.0.5 on 2022-07-07 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shikshalaya_computer_app', '0002_computer_course_computer_student_monthly_fees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer_student',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shikshalaya_computer_app.computer_course'),
        ),
    ]
